global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'hello-test'
    static_configs:
      - targets: ['host.docker.internal:3001']
  - job_name: 'hello-prod'
    static_configs:
      - targets: ['host.docker.internal:3002']
